CREATE TABLE providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(100) NOT NULL,
    city VARCHAR(120) NOT NULL,
    region VARCHAR(120),
    country VARCHAR(120) NOT NULL,
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    price_tier VARCHAR(50) NOT NULL,
    short_description TEXT,
    instagram_url VARCHAR(255),
    video_url VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(120),
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE provider_images (
    provider_id BIGINT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    image_order INTEGER NOT NULL,
    image_url VARCHAR(512) NOT NULL,
    PRIMARY KEY (provider_id, image_order)
);

CREATE TABLE inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    organizer_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(120),
    message TEXT,
    event_date DATE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
