spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventapp
    username: eventapp
    password: secret123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  port: 8080
