spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventapp
    username: eventapp
    password: secret123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  mail:
    host: smtp.example.com
    port: 587
    username: your-smtp-user
    password: your-smtp-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

admin:
  user:
    username: admin
    password: change-me

contact:
  admin-email: admin@example.com
